### ISSUE TITLE
Output reflects srcDir structure

### ISSUE THREAD

**Issue by ctzen** [kravemir/GradleSassPlugin#1]
Hi, first of all, great plugin!
Is it possible to generate the css files that reflects the directory structure of srcDir?
e.g. assuming `srcDir = '/src'` and `outDir = '/dst'`
`/src/app.scss` and `/src/foo/bar.scss` 
would generate respectively
`/dst/app.css` and `/dst/foo/bar.css` 
Regards.

**Comment by kravemir** [comment]
Hi,

thank you. It certainly should be possible to improve implementation in the way you've described.

I'm going to implement it.

With regards,
Miro

**Comment by kravemir** [comment]
It's fixed and the new version has been deployed to plugins.gradle.org.

See example: https://github.com/kravemir/GradleSassPlugin/tree/cba1e05e77682575428e8ab4d68816faee90eac2/examples/01-HelloSass

**Comment by ctzen** [comment]
Thank you.

**Comment by kravemir** [comment]
You're welcome. I'm glad you like the plugin. The feature you wanted is useful, worth implementing.

**Comment by ctzen** [comment]
Hi Miroslav,

Thank you again for the enhancement.

Another enhancement you may wish to consider is to produce both the 
minified, and non-minified css files at the same time,
so that dev can switch to the non-minified version for debugging.

I actually ended up implementing the plugin locally.  In addition to 
maintaining the directory structure (which you have implemented),
and outputting both minified and non-minified versions,
I also use the gradle IncrementalTaskInputs facility so that when a scss 
source is deleted, the target css is also deleted during build.

-cs

**Comment by kravemir** [comment]
@ctzen I have not yet needed this in my hobby projects, in which I use the plugin. However, in sounds to be useful when these projects are going to be production(publishing) ready.

You may open a pull request, if you would like to contribute. If not, then I will implement them on my own, some time later.
