### ISSUE TITLE
Not including imported files to compile

### ISSUE THREAD

**Issue by venkiiitk** [kravemir/GradleSassPlugin#10]
Hi ,
we have parent.scss and that import all child scss but this plugin not considering all child scss files 
is there any way to include child as well 
and also how to include multiple src and dest dirs ?

@import
"../../../test-core/scss/test-core",
"../vendor/vendor",
"../components/components";

**Comment by kravemir** [comment]
@venkiiitk, looks like you're referencing folders instead of specific sass files. Can you try importing sass files directly? Or, indirectly via some `..../index.scss` inside subfolders, which imports all scss files withing its folder?

**Comment by kravemir** [comment]
Hello @venkiiitk, I'm closing the issue as it was left unanswered for months now. If you're still experiencing issue, then feel free to open the issue and answer questions in previous comment.
