### ISSUE TITLE
Automated tests for plugin

### ISSUE THREAD

**Issue by eriwen** [kravemir/GradleSassPlugin#3]
It would benefit outside contributors to have automated tests so that we are sure we're not breaking plugin functionality.

I see that this plugin is written in pure Java (which is good). Would you still consider using [Gradle's TestKit](https://docs.gradle.org/current/userguide/test_kit.html) for functional testing? Are there other barriers to testing that Gradle could help out with?

**Comment by kravemir** [comment]
Looks to be very useful suggestion, I will definitively give it try. I've already accidentally broken a minor functionality once. This will save me a lot of time spent by manual testing using examples.

I try to keep frequently used code(tools, software, etc..) as light as possible, that was to reason to implement the plugin in pure Java.

**Comment by kravemir** [comment]
Tests have been added. Thanks for info.
