### ISSUE TITLE
how to exclude sass directory

### ISSUE THREAD

**Issue by minjay26** [kravemir/GradleSassPlugin#6]

**Comment by kravemir** [comment]
What exactly do yo mean? Please, provide better description - what's current behavior, what's expected behavior, what's current gradle configuration, what would you like to add/support.

**Comment by minjay26** [comment]
after compile,i want to exclude sass directory,and only css directory

**Comment by kravemir** [comment]
Exclude sass directory from what? By default, sass directory shouldn't be packaged/built into anything, unless you have put sass into src/resources directory.

Where is located your sass directory?

**Comment by minjay26** [comment]
yeah, you got it,my sass is located in src/resources directory

**Comment by kravemir** [comment]
Happens, see example [examples/03-JavaResources/build.gradle](https://github.com/kravemir/GradleSassPlugin/blob/master/examples/02-MultipleBuilds/build.gradle), might be useful.
